### ISSUE TITLE
npm update error?

### ISSUE THREAD

**Issue by MattAppleton** [tailwindtoolbox/StarterTemplate#2]
Hello and thanks for a fantastic resource... 

Just trying this now and I get a non-critical set of errors on npm update

`gyp: No Xcode or CLT version detected!`

Just wondering if Xcode needs to be installed? Can I ignore this? I already have the Command line tools installed...

**Comment by tailwindtoolbox** [comment]
Hey Matt, sorry haven't been logged into this account.
Deffo don't think you xcode to use tailwind css...
I'm assuming you are on a mac and recently updated to catalina? Based on this link, I'm guessing it could be linked to the terrible upgrade process? 🤣
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

**Comment by MattAppleton** [comment]
Hi there - -thanks so much for checking in on this — you are right, it turned out to be a Catalina glitch...
